[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "npm"
update_changelog_on_bump = true
major_version_zero = false
annotated_tag = true
post_bump_hooks = [
  "git push -u origin master --no-verify --follow-tags",
]

[tool.commitizen.customize]
bump_pattern = "^(break|new|fix|hotfix|build)"
bump_map = {"break" = "MAJOR", "new" = "MINOR", "fix" = "PATCH", "hotfix" = "PATCH", "build" = "PATCH"}
